site_name: Documentação - Prompt Enricher Backend
site_url: https://pradopha.github.io/prompt-enricher-backend/
nav:
  - Início: index.md
  - Instalação: instalacao.md
  - API: api.md
  - Estrutura do Projeto: estrutura.md
  - Serviços: servicos.md
  # - Fluxo de Execução: fluxo.md
theme:
  name: material
